ird_pdf_md_dir: data/ird_pdfs_md
object_dir: src/core/objects/preprocessed
output_filename: preprocessed
run_pdf_to_md: false
scrape_data: false
save_pickle: true
load_pickle: true
# index_name: my-nlp-preprocessed-index
queries:
  - "Which section of the Inland Revenue Ordinance imposed the basic charge of Salaries Tax?"
  - "Which 2 machinery or plants does the lease in included?"
  - "What does lease mean in legal term?"
  - "which section provides a form for double taxation relief?"